export const API_URL = "api.ff-legends.com/api/";

export const GET_RECOURSE_PATH = {
  USER_PROFILE: "profile",
  SEASONS_ALL: "seasons",
  ROUNDS_ALL: "rounds",
  ROUNDS_H2H: "hth-rounds",
  STANDINGS_ALL: "standings",
  STANDINGS_BY_LEAGUE: "standings",
  USER_PLAYERS_BY_USER: "champ_players",
  ADMIN_RESET_HALF: "?????",
  TRANSFERS_ALL: "transfer_all",
  TRANSFERS_PENDING: "transfer_pending",
  LEAGUES_ALL: "leagues",
  H2H_USERS_ALL: "hth-users",
  H2H_SEASON_MATCHING: "hth-matching",
  H2H_MATCHING_BY_ROUND: "hth-matching",
  H2H_TRANSFERS_ALL: "hth-transfers",
  H2H_TRANSFERS_PENDING: "hth-transfers-pending",
  SYNC_POINTS_FOR_ROUND: "sync_points",
  PLAYERS_ALL: "players",
  PLAYER_BY_ID: "players",
  PLAYERS_BY_LEAGUE: "players-league",
  FOOTBALL_LEAGUES_ALL: "football-leagues",
  CUP_GROUPS: "cup-groups",
  CUP_GROUPS_TEAMS: "cup-group-team",
  CUP_ROUNDS_ALL: "cup-rounds",
  CUP_STATS_BY_ROUNDS_AND_BY_USER: "cup-rounds-stats",
  CUP_SEASON_MATCHING: "cup-matching",
  CUP_MATCHING_BY_ROUND: "cup-matching",
};
